# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
lang: en-GB
title: Jo Petty's website
email: hello@jopetty.co.uk
description: "Jo Petty: Jo's Crochet"
baseurl: ""  # the subpath of your site, e.g. /blog
url: ""  # the base hostname & protocol for your site, e.g. http://example.com
author:
  name: Jo Petty
  instagram: joscrochet
  picture: /images/crochet-test.png
instagram_username: joscrochet
github_username: joscrochet
logo: /images/crochet-test.png
search: true
search_full_content: true

remote_theme: "mmistakes/jekyll-theme-basically-basic"